### ISSUE TITLE
Не работает DNS

### ISSUE THREAD

**Issue by ne-vlezay80** [medium-isp/medium-dns#4]
> ; <<>> DiG 9.10.3-P4-Debian <<>> -t aaaa search.medium.isp @200:d0c4:68ee:e87b:c206:67b8:5fa5:d4be
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 19705
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 4096
> ;; QUESTION SECTION:
> ;search.medium.isp.             IN      AAAA
> 
> ;; Query time: 19 msec
> ;; SERVER: 200:d0c4:68ee:e87b:c206:67b8:5fa5:d4be#53(200:d0c4:68ee:e87b:c206:67b8:5fa5:d4be)
> ;; WHEN: Mon Aug 19 14:34:34 MSK 2019
> ;; MSG SIZE  rcvd: 46

**Comment by podivilov** [comment]
Добрый день, технический сбой обусловлен обновлением серверов Medium. Мы отказываемся от удостоверяющих центров. Пожалуйста, сообщите, сейчас всё работает? Если да, то закройте, пожалуйста, тикет.
